package com.tamoino.web;

public enum RequestParameter {
	Action, WORD, KEY, VALID_WORD, NEW_WORD, GROUP_NAME, GROUP_ID, DELETED_WORD, NEW_GROUP_ID, NEW_GROUP_NAME, ACCOUNT_TYPE, EMAIL, PASSWORD, VALID_ACCOUNT, NEW_KEY, NEW_URL, NEW_ACTIVE, ADDITION_RESULT, DELETED_ENTRY, DELETION_RESULT, ACTIVE, ENTRY_ID, MESSAGE, MESSAGE_CLASS, EXCEPTION
}
